### ISSUE TITLE
It doesn't work well in real world.

### ISSUE THREAD

**Issue by hyclover** [ethz-asl/voxblox-plusplus#100]
Thanks for your great work! I run the example datasets and got satisfactory results. I want to build real environment semantic map with a handheld realsense D435i. However,  the camera pose should be provided. How should I get the camera pose? Which parameters should I change related to camera pose?

Currently, I utilize orb_slam2 with realsense D435i to provide pose information. Specifically, I download the orb_slam2_ros package and use the file _orb_slam2.launch_ . Here is my content of the launch file.
`arg name="visualize" default="true" 
 
include file="$(find gsm_node)/launch/vpp_pipeline.launch"
    arg name="scene_name" value="orb_slam2"
    arg name="sensor_name" value="realsense"
    arg name="visualize" value="$(arg visualize)"
/include
include file="$(find orb_slam2_ros)/ros/launch/orb_slam2_d435i_rgbd.launch
node pkg="tf" type="static_transform_publisher" name="base_to_camera" args="0 0 0 0 0 0 base_link camera_link 100"
` 
My first question: I additionally modified the last line _static_transform_publisher_, because I got warning message: 
> Could not find a connection between 'camera_link' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.
I'm not sure if it is right. Here is my tf tree:

![image](https://user-images.githubusercontent.com/44492334/119757957-4e409200-bed8-11eb-8616-b657a9dd655a.png)

My second question: I got the camera internal matrix by rosrun /camera/color/camera_info. Do I still need to calibrate the camera?

My execution steps are: `roslaunch realsense2_camera rs_rgbd.launch` and then `roslaunch gsm_node orb_slam2.launch`.
I got very bad results as follows. The bottom left image is label map and bottom right is real world picture. I found the label map is wrongly labeled. So my third question: how to improve depth segmentation results in real world? 
![image](https://user-images.githubusercontent.com/44492334/119756552-45e75780-bed6-11eb-8105-68f14c403c86.png)

 I would appreciate it if you could reply. Thanks!

**Comment by hyclover** [comment]
@margaritaG

**Comment by margaritaG** [comment]
Hi @hyclover,

Voxblox++ does not estimate the camera pose, so you definitely should rely on a third-party framework for that, such as ORB_SLAM2. 

With regards to camera calibration, I guess you are currently just reading out the factory calibration parameters (unless you or someone else have previously calibrated it an written to the device the new, better parameters). Whether to calibrate the camera or use the factory parameters depends on your applications and how much do you care about the accuracy of your maps.

Lastly, your main issue seems to be depth_segmentation not being tuned to your type of scenes. I recommend using dynamic reconfigure to play with the parameters of the depth_segmentation node, such as normals_window_size, depth_discontinuity_ratio, max_distance_window_size, max_distance_noise_thresholding_factor, min_convexity_window_size, min_convexity_threshold, label_min_size, etc.

Tune the parameters until you get satisfactory per-frame segmentation results, and then try again running the full Voxblox++ stack. Remember to dump the depth_segmentation parameters to a file, else next time you restart ROS you will revert back to the default parameters without a way of restoring you preferred values.
