### ISSUE TITLE
[gsm_node-3] process has died.

### ISSUE THREAD

**Issue by calmelo** [ethz-asl/voxblox-plusplus#101]
roslaunch gsm_node vpp_pipeline.launch, error: [gsm_node-3] process has died.

**Comment by margaritaG** [comment]
@calmelo I am going to need some more information to help you debug the issue. 

Does the node die immediately after start? Did you try running the Voxblox++ node in GDB to see where the issue occurs? (http://wiki.ros.org/roslaunch/Tutorials/Roslaunch%20Nodes%20in%20Valgrind%20or%20GDB)
