### ISSUE TITLE
Semantic depth segmentation does not work

### ISSUE THREAD

**Issue by elijah-ortiz** [ethz-asl/voxblox-plusplus#106]
First of all thank you so much for a great ROS framework! It has everything I've been looking for in a package, and I have gotten in 90% of the way there but I cannot get the semantic version of the depth segmentation node to work properly.

I cannot seem to get the VPP pipeline to work correctly with the semantic_depth_segmentation.launch file. The pipeline runs fine and constructs a map when I substitute the semantic depth with the geometric depth launchfile, although obviously I lose the semantic information which I would like very much to have. 

MASK-RCNN is built correctly, launches, and I am able to see the visualization in rviz as well. I have manually downloaded the coco weights replaced the automatically downloaded version as well due to loading errors. 

I've tried to reopen a previous issue from the depth_segmentation repo to see if I could get help there, as the issue seems to be in that node. Any help would be appreciated here, as I think it must be something so minor. Thank you so much!

https://github.com/ethz-asl/depth_segmentation/issues/54

**Comment by QuantumY-CHN** [comment]
Hello, I'm struggling in a similar situation, and I can identify my problem occurs in the 'LabelMap'. Could the problem be related to the OpenCV version conflict? Would it be possible for you to share the solution? Thanks!
