### ISSUE TITLE
When I compile the packages,there is a problem

### ISSUE THREAD

**Issue by Ljh0121** [ethz-asl/voxblox-plusplus#51]
Errors     << depth_segmentation:make /home/yu3/catkin_ws/logs/depth_segmentation/build.make.000.log                                      
/home/yu3/catkin_ws/src/depth_segmentation/depth_segmentation/src/depth_segmentation_node.cpp: In member function ‘void DepthSegmentationNode::imageSegmentationCallback(const ConstPtr&, const ConstPtr&, const ConstPtr&)’:
/home/yu3/catkin_ws/src/depth_segmentation/depth_segmentation/src/depth_segmentation_node.cpp:552:50: error: no matching function for call to ‘DepthSegmentationNode::preprocess(const ConstPtr&, const ConstPtr&, cv::Mat*, cv_bridge::CvImagePtr&, cv_bridge::CvImagePtr&, cv::Mat*, cv::Mat*)’
                  cv_depth_image, &bw_image, &mask);
                                                  ^
/home/yu3/catkin_ws/src/depth_segmentation/depth_segmentation/src/depth_segmentation_node.cpp:354:8: note: candidate: void DepthSegmentationNode::preprocess(const ConstPtr&, const ConstPtr&, cv::Mat*, cv::Mat*, cv_bridge::CvImagePtr, cv_bridge::CvImagePtr, cv::Mat*, cv::Mat*)
   void preprocess(const sensor_msgs::Image::ConstPtr& depth_msg,
        ^
/home/yu3/catkin_ws/src/depth_segmentation/depth_segmentation/src/depth_segmentation_node.cpp:354:8: note:   candidate expects 8 arguments, 7 provided
make[2]: *** [CMakeFiles/depth_segmentation_node.dir/src/depth_segmentation_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/depth_segmentation_node.dir/all] Error 2
make: *** [all] Error 2
cd /home/yu3/catkin_ws/build/depth_segmentation; catkin build --get-env depth_segmentation | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
..........................................................................................................................................
Failed     << depth_segmentation:make             [ Exited with code 2 ]                                                                  
Failed    <<< depth_segmentation                  [ 18.7 seconds ]                                                                        
Abandoned <<< gsm_node                            [ Unrelated job failed ]                                                                
Finished  <<< voxblox_ros                         [ 59.7 seconds ]

**Comment by margaritaG** [comment]
Hi @Ljh0121, thanks for letting us know about this!

The issue should be resolved in https://github.com/ethz-asl/depth_segmentation/pull/45. Please pull the latest master of the `depth_segmentation` package as follows:
```
cd $CATKIN_WS/src/depth_segmentation
git pull origin master
```

 and try building again with

```
catkin build mask_rcnn_ros depth_segmentation gsm_node
```
