### ISSUE TITLE
How to get bounding box  according to the values in 'oobox' area of  scenenn dataset?

### ISSUE THREAD

**Issue by BenChenCh** [ethz-asl/voxblox-plusplus#54]
Thank you for your great work! 
My question is how to calculate a bounding box from the values in 'obbox' area?
In order to calculate the IoU, I need to get all the ground truth object bounding box.
![Screenshot from 2019-11-02 20-57-18](https://user-images.githubusercontent.com/12813396/68071226-6828fa00-fdb3-11e9-9451-c2942fcd08ac.png)
Because there are only 10 values in 'oobbox' area, which 10 can not  be divided with by 3( a xyz point)?

**Comment by margaritaG** [comment]
@BenChenCh I haven't worked with bounding boxes of the SceneNN dataset, therefore I do not know what these 10 values represent.

You should ask to the authors of SceneNN directly.

**Comment by margaritaG** [comment]
@BenChenCh I stumbled upon this comment from the authors on the main page of the SceneNN project http://www.scenenn.net:

The format of the object-oriented bounding box is: 
box center (x, y, z), box dimension (along x, y, z), and a quaternion (x, y, z, w) that represents the rotation of the box.

Hope this helps.
