### ISSUE TITLE
catkin build problem

### ISSUE THREAD

**Issue by wolf943134497** [ethz-asl/voxblox-plusplus#60]
Hi @margaritaG  Thanks for your great works!
I have a strange problem, when I run catkin build -j12,  the package can not build success! The build process hang long time! the runtime is 7 hours 42 minutes and 50.9 seconds total. no error log In process. 

17 of 24 packages succeeded.

any suggestion?
Thanks!

**Comment by margaritaG** [comment]
@wolf943134497 it could be that compilation of pcl_catkin (namely, its pcl_ros package) it running low on RAM, see [here](https://github.com/ethz-asl/voxblox-plusplus/wiki/Installation-on-Ubuntu#compilation-freeze). 

How many CPU cores does your machine have? Try limiting the number of parallel jobs via the -j flag to something that is way lower that your total number of cores.

**Comment by wolf943134497** [comment]
@margaritaG  Thank you for your feedback! 
my machine have 16 cores. I try  to use 4,6,8,12  parallel jobs,but the problem still can not be solved! I have the same problem when I use pcl_catkin in other project.

**Comment by margaritaG** [comment]
@wolf943134497 Did you try `catkin build mask_rcnn_ros depth_segmentation gsm_node -j1 -l1`?

**Comment by wolf943134497** [comment]
> @wolf943134497 Did you try `catkin build mask_rcnn_ros depth_segmentation gsm_node -j1 -l1`?

@margaritaG  Thanks your suggestions! It works after trying -j1 - 11
