### ISSUE TITLE
hello,when I build,a error appear :error: static assertion failed

### ISSUE THREAD

**Issue by resplendent-star** [ethz-asl/voxblox-plusplus#66]
ubuntu 18.04

console output：

____________________________________________________________________________________________________________________________________
Errors     << pcl_catkin:make /home/lzw/resplendent_code/voxblox_pp_ws/logs/pcl_catkin/build.make.004.log                            
In file included from /usr/local/include/eigen3/Eigen/Core:153:0,
                 from /home/lzw/resplendent_code/voxblox_pp_ws/build/pcl_catkin/pcl_src-prefix/src/pcl_src/common/include/pcl/impl/point_types.hpp:46,
                 from /home/lzw/resplendent_code/voxblox_pp_ws/build/pcl_catkin/pcl_src-prefix/src/pcl_src/common/include/pcl/point_types.h:359,
                 from /home/lzw/resplendent_code/voxblox_pp_ws/build/pcl_catkin/pcl_src-prefix/src/pcl_src/filters/include/pcl/filters/frustum_culling.h:42,
                 from /home/lzw/resplendent_code/voxblox_pp_ws/build/pcl_catkin/pcl_src-prefix/src/pcl_src/filters/include/pcl/filters/impl/frustum_culling.hpp:41,
                 from /home/lzw/resplendent_code/voxblox_pp_ws/build/pcl_catkin/pcl_src-prefix/src/pcl_src/filters/src/frustum_culling.cpp:38:
/usr/local/include/eigen3/Eigen/src/Core/Dot.h: In instantiation of ‘typename Eigen::ScalarBinaryOpTraits<typename Eigen::internal::traits<T>::Scalar, typename Eigen::internal::traits<OtherDerived>::Scalar>::ReturnType Eigen::MatrixBase<Derived>::dot(const Eigen::MatrixBase<OtherDerived>&) const [with OtherDerived = Eigen::Block<Eigen::Matrix<float, 4, 1>, -1, -1, false>; Derived = Eigen::Matrix<float, 3, 1>; typename Eigen::ScalarBinaryOpTraits<typename Eigen::internal::traits<T>::Scalar, typename Eigen::internal::traits<OtherDerived>::Scalar>::ReturnType = float]’:
/home/lzw/resplendent_code/voxblox_pp_ws/build/pcl_catkin/pcl_src-prefix/src/pcl_src/filters/include/pcl/filters/impl/frustum_culling.hpp:113:24:   required from ‘void pcl::FrustumCulling<PointT>::applyFilter(std::vector<int>&) [with PointT = pcl::PointXYZ]’
/home/lzw/resplendent_code/voxblox_pp_ws/build/pcl_catkin/pcl_src-prefix/src/pcl_src/filters/src/frustum_culling.cpp:44:1:   required from here
/usr/local/include/eigen3/Eigen/src/Core/Dot.h:75:3: error: static assertion failed: YOU_TRIED_CALLING_A_VECTOR_METHOD_ON_A_MATRIX
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(OtherDerived)
   ^
make[5]: *** [filters/CMakeFiles/pcl_filters.dir/src/frustum_culling.cpp.o] Error 1
make[4]: *** [filters/CMakeFiles/pcl_filters.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [pcl_src-prefix/src/pcl_src-stamp/pcl_src-build] Error 2
make[1]: *** [CMakeFiles/pcl_src.dir/all] Error 2
make: *** [all] Error 2

**Comment by resplendent-star** [comment]
![error eigen](https://user-images.githubusercontent.com/41502003/76276420-bea5c800-62c0-11ea-96bc-f6853c506f3a.png)

**Comment by margaritaG** [comment]
@resplendent-star it seems a known issue from the PCL library: https://github.com/PointCloudLibrary/pcl/pull/2786

Since the issue should be fixed starting from PCL 1.10 (so far Voxblox++ was fetching PCL 1.9.1) I have merged in a PR to request PCL 1.10.1, see https://github.com/ethz-asl/voxblox-plusplus/pull/68

For this to take effect on your machine you should pull the latest voxblox++ master, then `wstool merge -t . voxblox-plusplus/voxblox-plusplus_https.rosinstall`

It should ask something along the lines of: 

```
$ wstool merge -t . voxblox-plusplus/voxblox-plusplus_https.rosinstall

     Change details of element (Use --merge-keep or --merge-replace to change):
  pcl_catkin

Continue: (y)es, (n)o, (v)erbosity, (a)dvanced options: 

```
After answering yes, run `wstool update`.

Else, you can just manually checkout the branch fix/advance_perception_pcl in the pcl_catkin folder.

Let me know if the issue persists.

**Comment by resplendent-star** [comment]
wstool merge -t . voxblox-plusplus/voxblox-plusplus_https.rosinstall
ERROR in config: /home/lzw/resplendent_code/voxblox_pp_ws has no workspace configuration file '.rosinstall'

**Comment by resplendent-star** [comment]
> @resplendent-star it seems a known issue from the PCL library: [PointCloudLibrary/pcl#2786](https://github.com/PointCloudLibrary/pcl/pull/2786)
> 
> Since the issue should be fixed starting from PCL 1.10 (so far Voxblox++ was fetching PCL 1.9.1) I have merged in a PR to request PCL 1.10.1, see #68
> 
> For this to take effect on your machine you should pull the latest voxblox++ master, then `wstool merge -t . voxblox-plusplus/voxblox-plusplus_https.rosinstall`
> 
> It should ask something along the lines of:
> 
> ```
> $ wstool merge -t . voxblox-plusplus/voxblox-plusplus_https.rosinstall
> 
>      Change details of element (Use --merge-keep or --merge-replace to change):
>   pcl_catkin
> 
> Continue: (y)es, (n)o, (v)erbosity, (a)dvanced options: 
> ```
> 
> After answering yes, run `wstool update`.
> 
> Else, you can just manually checkout the branch fix/advance_perception_pcl in the pcl_catkin folder.
> 
> Let me know if the issue persists.

lzw@resplendent-star:~/resplendent_code/voxblox_pp_ws/src$  wstool merge -t . voxblox-plusplus/voxblox-plusplus_https.rosinstall
Merge caused no change, no new elements found

**Comment by margaritaG** [comment]
Please try to manually checkout the `master` branch in the `pcl_catkin` package.

Something along these lines:
```
$ cd pcl_catkin
$ git checkout master
$ git pull origin master
```

Then, just to be sure, run `catkin clean` and finally try to build again.

If all else fails, just delete your voxblox++ workspace and try a clean install.

**Comment by resplendent-star** [comment]
> Please try to manually checkout the `master` branch in the `pcl_catkin` package.
> 
> Something along these lines:
> 
> ```
> $ cd pcl_catkin
> $ git checkout master
> $ git pull origin master
> ```
> 
> Then, just to be sure, run `catkin clean` and finally try to build again.
> 
> If all else fails, just delete your voxblox++ workspace and try a clean install.

hello,I  try all  this command  in  old pal_catkin

return "fatal: not a git repository (or any parent directory): .git"


and  then  I  creat  a new  voxblox++ workspace,when do catkin build
still  return  "EIGEN_STATIC_ASSERT_VECTOR_ONLY(OtherDerived)"

then I  use  "git checkout master"

still return "fatal: not a git repository (or any parent directory): .git"

**Comment by margaritaG** [comment]
That is not an error I can help you resolve as it just seems you are running the commands from the wrong folder. Are you sure you are running the git checkout command from the `pcl_catkin` folder? it seems like you are running it from somewhere else, like you `src` folder. 

Did you do a complete wipe of the workspace and newly cloned the voxblox++ repository? If yes, and the issue still persists then can you post the output of `$ git branch` run from the pcl_catkin folder.

**Comment by resplendent-star** [comment]
> That is not an error I can help you resolve as it just seems you are running the commands from the wrong folder. Are you sure you are running the git checkout command from the `pcl_catkin` folder? it seems like you are running it from somewhere else, like you `src` folder.
> 
> Did you do a complete wipe of the workspace and newly cloned the voxblox++ repository? If yes, and the issue still persists then can you post the output of `$ git branch` run from the pcl_catkin folder.

hello
,this  output 
1)
lzw@resplendent-star:~/resplendent_code/voxblox_pp_ws/build/pcl_catkin$ git checkout master
fatal: 不是一个 git 仓库（或者任何父目录）：.git

this info in english is:[fatal: not a git repository (or any parent directory): .git]


2)lzw@resplendent-star:~/resplendent_code/voxblox_pp_ws/build/pcl_catkin$ git branch
fatal: 不是一个 git 仓库（或者任何父目录）：.git
this info in english is:[fatal: not a git repository (or any parent directory): .git]

**Comment by margaritaG** [comment]
Finally, I see what is the problem: you are not supposed to work from the build space but from the `src` folder in your workspace.

That is, not from `~/resplendent_code/voxblox_pp_ws/build/pcl_catkin` but from `~/resplendent_code/voxblox_pp_ws/src/pcl_catkin`.

If you want to use Voxblox++ but you are not familiar with ROS and catkin, I would first highly encourage you to learn about them [here](https://www.ros.org) and [here](http://wiki.ros.org/catkin).

**Comment by resplendent-star** [comment]
> Finally, I see what is the problem: you are not supposed to work from the build space but from the `src` folder in your workspace.
> 
> That is, not from `~/resplendent_code/voxblox_pp_ws/build/pcl_catkin` but from `~/resplendent_code/voxblox_pp_ws/src/pcl_catkin`.
> 
> If you want to use Voxblox++ but you are not familiar with ROS and catkin, I would first highly encourage you to learn about them [here](https://www.ros.org) and [here](http://wiki.ros.org/catkin).

thank you 

(base) lzw@resplendent-star:~/resplendent_code/voxblox_pp_ws/src/pcl_catkin$ git checkout master
切换到分支 'master'
您的分支与上游分支 'origin/master' 一致。
(base) lzw@resplendent-star:~/resplendent_code/voxblox_pp_ws/src/pcl_catkin$ git pull origin master
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 13 (delta 5), reused 8 (delta 3), pack-reused 0
展开对象中: 100% (13/13), 完成.
来自 https://github.com/ethz-asl/pcl_catkin
 * branch            master     -> FETCH_HEAD
   23a38b5..2a70959  master     -> origin/master
Fetching submodule perception_pcl
来自 https://github.com/ethz-asl/perception_pcl
   c58e92c..6d7afe2  melodic-devel -> origin/melodic-devel
更新 23a38b5..2a70959
Fast-forward
 pcl_catkin/CMakeLists.txt            | 4 ++--
 pcl_catkin/cmake/pcl-extras.cmake.in | 4 ++--
 pcl_catkin/package.xml               | 2 +-
 perception_pcl                       | 2 +-
 4 files changed, 6 insertions(+), 6 deletions(-)
(base) lzw@resplendent-star:~/resplendent_code/voxblox_pp_ws/src/pcl_catkin$

**Comment by margaritaG** [comment]
I hope this solved the PCL build issue. Closing, feel free to reopen if the issue persists.
