### ISSUE TITLE
hello， voxblox::SimulationWorld::objects_’ is private within this context

### ISSUE THREAD

**Issue by resplendent-star** [ethz-asl/voxblox-plusplus#67]
when  I  build MIT kimera with vox++，occurs error
_________________________________________________________________________________
Errors     << kimera_semantics:make /home/lzw/resplendent_code/k_s_ros1_ws/logs/kimera_semantics/build.make.000.log
/home/lzw/resplendent_code/k_s_ros1_ws/src/Kimera-Semantics/kimera_semantics/src/simulation/semantic_simulation_world.cpp: In member function ‘void kimera::SemanticSimulationWorld::generateSemanticSdfFromWorld(voxblox::FloatingPoint, voxblox::Layer<kimera::SemanticVoxel>*)’:
/home/lzw/resplendent_code/k_s_ros1_ws/src/Kimera-Semantics/kimera_semantics/src/simulation/semantic_simulation_world.cpp:84:57: error: ‘std::__cxx11::list<std::unique_ptr<voxblox::Object> > voxblox::SimulationWorld::objects_’ is private within this context
       for (const std::unique_ptr<vxb::Object>& object : objects_) {
                                                         ^~~~~~~~
In file included from /home/lzw/resplendent_code/k_s_ros1_ws/src/Kimera-Semantics/kimera_semantics/include/kimera_semantics/simulation/semantic_simulation_world.h:1:0,
                 from /home/lzw/resplendent_code/k_s_ros1_ws/src/Kimera-Semantics/kimera_semantics/src/simulation/semantic_simulation_world.cpp:1:
/home/lzw/resplendent_code/k_s_ros1_ws/src/voxblox/voxblox/include/voxblox/simulation/simulation_world.h:102:39: note: declared private here
   std::list<std::unique_ptr<Object> > objects_;
                                       ^~~~~~~~
/home/lzw/resplendent_code/k_s_ros1_ws/src/Kimera-Semantics/kimera_semantics/src/simulation/semantic_simulation_world.cpp:88:39: error: ‘class voxblox::Object’ has no member named ‘getType’; did you mean ‘Type’?
           selectSemanticLabel(object->getType(), &semantic_label);
                                       ^~~~~~~
                                       Type
make[2]: *** [CMakeFiles/kimera_semantics.dir/src/simulation/semantic_simulation_world.cpp.o] Error 1
make[2]: *** 正在等待未完成的任务....
make[1]: *** [CMakeFiles/kimera_semantics.dir/all] Error 2
make: *** [all] Error 2
cd /home/lzw/resplendent_code/k_s_ros1_ws/build/kimera_semantics; catkin build --get-env kimera_semantics | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
..................................................................................
Failed     << kimera_semantics:make               [ Exited with code 2 ]          
Failed    <<< kimera_semantics                    [ 3.7 seconds ]                 
Abandoned <<< voxblox_ros                         [ Unrelated job failed ]        
Abandoned <<< kimera_semantics_ros                [ Unrelated job failed ]        
Finished  <<< voxblox_rviz_plugin                 [ 11.5 seconds ]                
[build] Summary: 11 of 14 packages succeeded.                                     
[build]   Ignored:   22 packages were skipped or are blacklisted.                 
[build]   Warnings:  2 packages succeeded with warnings.                          
[build]   Abandoned: 2 packages were abandoned.                                   
[build]   Failed:    1 packages failed.                                           
[build] Runtime: 28.1 seconds total.                                              
[build] Note: Workspace packages have changed, please re-source setup files to use them.
lzw@resplendent-star:~/resplendent_code/k_s_ros1_ws$ 
![kimeraerror](https://user-images.githubusercontent.com/41502003/76276645-615e4680-62c1-11ea-8c6d-5d159547d157.png)

**Comment by chyohoo** [comment]
I got the same problems .

**Comment by chyohoo** [comment]
check out this[https://github.com/MIT-SPARK/Kimera-Semantics/issues/10](url)

**Comment by chyohoo** [comment]
check this https://github.com/MIT-SPARK/Kimera-Semantics/issues/10#issuecomment-590081946

**Comment by margaritaG** [comment]
@resplendent-star you are trying to build Kimera-Semantics, which is a separate framework from Voxblox++ (even though they both share a common ancestor which is Voxblox).

As chyohoo suggested, you should check directly with the Kimera-Semantics authors.

**Comment by resplendent-star** [comment]
thanks  for  reply！------------------ 原始邮件 ------------------
发件人: "Margarita Grinvald"<notifications@github.com>
发送时间: 2020年3月26日(星期四) 晚上6:54
收件人: "ethz-asl/voxblox-plusplus"<voxblox-plusplus@noreply.github.com>;
抄送: "resplendent-star"<485434977@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [ethz-asl/voxblox-plusplus] hello， voxblox::SimulationWorld::objects_’ is private within this context (#67)




 
@resplendent-star you are trying to build Kimera-Semantics, which is a separate framework from Voxblox++ (even though they both share a common ancestor which is Voxblox).
 
As chyohoo suggested, you should check directly with the Kimera-Semantics authors.
 
&mdash;
