### ISSUE TITLE
save map

### ISSUE THREAD

**Issue by jguan2984-1** [ethz-asl/voxblox-plusplus#75]
Hi,
How could save the generated semantic 3D map as .ply file or other format?

**Comment by nonlinear1** [comment]
Do you compile the voxblox-plusplus, successfully.

**Comment by margaritaG** [comment]
@jguan2984-1 

To answer your question I documented the `generate_mesh` service here: https://github.com/ethz-asl/voxblox-plusplus/wiki/The-voxblox-plusplus-node

It is exactly what you need to retrieve the reconstructed map as a PLY file.

I hope that this will mark the beginning of an effort from my side to document the functionality of the node :)
