### ISSUE TITLE
Does this error matter? 

### ISSUE THREAD

**Issue by nonlinear1** [ethz-asl/voxblox-plusplus#76]
When I use "catkin build mask_rcnn_ros depth_segmentation gsm_node -j4" to compile, I get errors:
Warnings   << pcl_ros:cmake /home/manifold/catkin_ws/logs/pcl_ros/build.cmake.004.log                                            
CMake Warning at /home/manifold/catkin_ws/devel/share/pcl_catkin/cmake/pcl-extras.cmake:14 (find_package):
  By not providing "FindQVTK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "QVTK", but
  CMake did not find one.

  Could not find a package configuration file provided by "QVTK" with any of
  the following names:

    QVTKConfig.cmake
    qvtk-config.cmake

  Add the installation prefix of "QVTK" to CMAKE_PREFIX_PATH or set
  "QVTK_DIR" to a directory containing one of the above files.  If "QVTK"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /home/manifold/catkin_ws/devel/share/pcl_catkin/cmake/pcl_catkinConfig.cmake:222 (include)
  CMakeLists.txt:10 (find_package)

cd /home/manifold/catkin_ws/build/pcl_ros; catkin build --get-env pcl_ros | catkin env -si  /usr/local/bin/cmake /home/manifold/catkin_ws/src/pcl_catkin/perception_pcl/pcl_ros --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/manifold/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/home/manifold/catkin_ws/install -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=Release; cd -
.................................................................................................................................
Does this error matter?

**Comment by margaritaG** [comment]
@nonlinear1 I also do get the exact same warning on my machine all the time. I haven't looked into it in detail, but it is related to PCL, VTK, and potentially pcl_catkin.

Anyhow, it is not harmful and it has never impacted me so far.
