### ISSUE TITLE
Got white screen in basic usage demo

### ISSUE THREAD

**Issue by k123jack** [ethz-asl/voxblox-plusplus#77]
After running :
roslaunch gsm_node scenenn_dataset.launch bag_file:=/disk/data/asl_office_floor.bag

get an error like :
.[mask_rcnn-1] process has died [pid 22248, exit code 1, cmd /home/kaku/voxbloxpp/src/mask_rcnn_ros/scripts/mask_rcnn_node.py ~input:=rgb_image_sub_topic __name:=mask_rcnn __log:=/home/kaku/.ros/log/4752233e-8bf1-11ea-8b0b-a85e4517ddb5/mask_rcnn-1.log].
log file: /home/kaku/.ros/log/4752233e-8bf1-11ea-8b0b-a85e4517ddb5/mask_rcnn-1*.log

but it can still keep running, and continuously outputs like : 

 [RUNNING]  Bag Time: 1550161127.001316   Duration: 0.000000 / 307.839805        [RUNNING]  Bag Time: 1550161127.001332   Duration: 0.000016 / 307.839805        [RUNNING]  Bag Time: 1550161127.021358   Duration: 0.020042 / 307.839805        [RUNNING]  Bag Time: 1550161127.031921   Duration: 0.030605 / 307.839805        [RUNNING]  Bag Time: 1550161127.041917   Duration: 0.040601 / 307.839805        [RUNNING]  Bag Time: 1550161127.061944   Duration: 0.060628 / 307.839805        [RUNNING]  Bag Time: 1550161127.062135   Duration: 0.060818 / 307.839805        [RUNNING]  Bag Time: 1550161127.072261   Duration: 0.070945 / 307.839805        [RUNNING]  Bag Time: 1550161127.082317   Duration: 0.081001 / 307.839805        [RUNNING]  Bag Time: 1550161127.102342   Duration: 0.101026 / 307.839805 

But the window "Mp1" is a white screen showing no result.

**Comment by jguan2984-1** [comment]
> After running :
> roslaunch gsm_node scenenn_dataset.launch bag_file:=/disk/data/asl_office_floor.bag
> 
> get an error like :
> .[mask_rcnn-1] process has died [pid 22248, exit code 1, cmd /home/kaku/voxbloxpp/src/mask_rcnn_ros/scripts/mask_rcnn_node.py ~input:=rgb_image_sub_topic __name:=mask_rcnn __log:=/home/kaku/.ros/log/4752233e-8bf1-11ea-8b0b-a85e4517ddb5/mask_rcnn-1.log].
> log file: /home/kaku/.ros/log/4752233e-8bf1-11ea-8b0b-a85e4517ddb5/mask_rcnn-1*.log
> 
> but it can still keep running, and continuously outputs like :
> 
> [RUNNING] Bag Time: 1550161127.001316 Duration: 0.000000 / 307.839805 [RUNNING] Bag Time: 1550161127.001332 Duration: 0.000016 / 307.839805 [RUNNING] Bag Time: 1550161127.021358 Duration: 0.020042 / 307.839805 [RUNNING] Bag Time: 1550161127.031921 Duration: 0.030605 / 307.839805 [RUNNING] Bag Time: 1550161127.041917 Duration: 0.040601 / 307.839805 [RUNNING] Bag Time: 1550161127.061944 Duration: 0.060628 / 307.839805 [RUNNING] Bag Time: 1550161127.062135 Duration: 0.060818 / 307.839805 [RUNNING] Bag Time: 1550161127.072261 Duration: 0.070945 / 307.839805 [RUNNING] Bag Time: 1550161127.082317 Duration: 0.081001 / 307.839805 [RUNNING] Bag Time: 1550161127.102342 Duration: 0.101026 / 307.839805
> 
> But the window "Mp1" is a white screen showing no result.

it seems that there is a problem with calling the node mask_rcnn
Maybe you should check if you have installed tensor-flow gpu successfully.

**Comment by k123jack** [comment]
@jguan2984-1 

Hi
I think it was due to the pipeline has began to calculate while the maskrcnn weights are still downloading. I solved this by manually download the weights.
 
However, the depth segmentation node also made an error. "Mp1" is still white screen showing no result.

[RUNNING]  Bag Time:      3.019437   Duration: 2.985921 / 186.315444            
[RUNNING]  Bag Time:      3.052285   Duration: 3.018769 / 186.315444           [depth_segmentation_node-2] process has died [pid 7067, exit code -6, cmd /home/user1/voxbloxpp/devel/lib/depth_segmentation/depth_segmentation_node __name:=depth_segmentation_node __log:=/home/user1/.ros/log/20ee6116-91b5-11ea-9d93-a85e4517ddb5/depth_segmentation_node-2.log].
log file: /home/user1/.ros/log/20ee6116-91b5-11ea-9d93-a85e4517ddb5/depth_segmentation_node-2*.log
 [RUNNING]  Bag Time:      3.084338   Duration: 3.050822 / 186.315444            
[RUNNING]  Bag Time:      3.117950   Duration: 3.084434 / 186.315444   

Thx

**Comment by k123jack** [comment]
Worked, Thx

**Comment by zoe4751** [comment]
> After running :
> roslaunch gsm_node scenenn_dataset.launch bag_file:=/disk/data/asl_office_floor.bag
> 
> get an error like :
> .[mask_rcnn-1] process has died [pid 22248, exit code 1, cmd /home/kaku/voxbloxpp/src/mask_rcnn_ros/scripts/mask_rcnn_node.py ~input:=rgb_image_sub_topic __name:=mask_rcnn __log:=/home/kaku/.ros/log/4752233e-8bf1-11ea-8b0b-a85e4517ddb5/mask_rcnn-1.log].
> log file: /home/kaku/.ros/log/4752233e-8bf1-11ea-8b0b-a85e4517ddb5/mask_rcnn-1*.log
> 
> but it can still keep running, and continuously outputs like :
> 
> [RUNNING] Bag Time: 1550161127.001316 Duration: 0.000000 / 307.839805 [RUNNING] Bag Time: 1550161127.001332 Duration: 0.000016 / 307.839805 [RUNNING] Bag Time: 1550161127.021358 Duration: 0.020042 / 307.839805 [RUNNING] Bag Time: 1550161127.031921 Duration: 0.030605 / 307.839805 [RUNNING] Bag Time: 1550161127.041917 Duration: 0.040601 / 307.839805 [RUNNING] Bag Time: 1550161127.061944 Duration: 0.060628 / 307.839805 [RUNNING] Bag Time: 1550161127.062135 Duration: 0.060818 / 307.839805 [RUNNING] Bag Time: 1550161127.072261 Duration: 0.070945 / 307.839805 [RUNNING] Bag Time: 1550161127.082317 Duration: 0.081001 / 307.839805 [RUNNING] Bag Time: 1550161127.102342 Duration: 0.101026 / 307.839805
> 
> But the window "Mp1" is a white screen showing no result.

Hey，I have met the same problem like you, after ruuning "roslaunch gsm_node"
get an error like :
[mask_rcnn-1] process has died [pid 22248, exit code 1, cmd 

you said you solved this by manually download the weights, do you mean you download "mask_rcnn_coco.h5" by yourself and copy it to the folder "～./ros"？
