### ISSUE TITLE
pcl_ros at 100%  freeze

### ISSUE THREAD

**Issue by nonlinear1** [ethz-asl/voxblox-plusplus#78]
When I compile this voxblox-plusplus, I found that the pcl_ros package freezes at 100%. How to solve? see the following picture:
![Screenshot from 2020-05-07 06-42-09](https://user-images.githubusercontent.com/19766939/81235997-cbc80480-902e-11ea-8076-32b3abc4d6b3.png)

Anyone know how to solve? Thanks, a lot.

**Comment by jguan2984-1** [comment]
> When I compile this voxblox-plusplus, I found that the pcl_ros package freezes at 100%. How to solve? see the following picture:
> ![Screenshot from 2020-05-07 06-42-09](https://user-images.githubusercontent.com/19766939/81235997-cbc80480-902e-11ea-8076-32b3abc4d6b3.png)
> 
> Anyone know how to solve? Thanks, a lot.

Hi, 
I suppose you just run "catkin build mask_rcnn_ros depth_segmentation gsm_node" with multiple cores?
You just need to run:
catkin clean
catkin build mask_rcnn_ros depth_segmentation gsm_node -j1

That works for me.

**Comment by nonlinear1** [comment]
Thank you very much ! I will try.

**Comment by nonlinear1** [comment]
I run: catkin build mask_rcnn_ros depth_segmentation gsm_node -j1 for a day. And freezes for about a day. See the following picture:
![Uploading Screenshot from 2020-05-08 23-42-40.png…]()




Could some one know how to solve?

**Comment by margaritaG** [comment]
For anyone experiencing the same issue, make sure to checkout out [this Wiki entry](https://github.com/ethz-asl/voxblox-plusplus/wiki/Installation-on-Ubuntu#compilation-freeze-see-this-issue) and try running:
```
catkin build mask_rcnn_ros depth_segmentation gsm_node -j1 -l1
```
