### ISSUE TITLE
Freezes when I compile, how to solve?

### ISSUE THREAD

**Issue by nonlinear1** [ethz-asl/voxblox-plusplus#79]
I run: catkin build mask_rcnn_ros depth_segmentation gsm_node -j1 for a day. And freezes for about a day. See the following picture:
![Screenshot from 2020-05-08 23-42-40](https://user-images.githubusercontent.com/19766939/81423274-dac1ca80-9186-11ea-8a7c-1e583af24a4c.png)
Someone know how to solve? Thank you very much!

**Comment by margaritaG** [comment]
@nonlinear1 Did you try to follow what suggested in in the Troubleshooting Wiki: https://github.com/ethz-asl/voxblox-plusplus/wiki/Installation-on-Ubuntu#compilation-freeze-see-this-issue

That is, try to also to limit the max load as:
```
catkin build mask_rcnn_ros depth_segmentation gsm_node -j1 -l1
```

**Comment by nonlinear1** [comment]
Thank you very much, I will try once more

**Comment by nonlinear1** [comment]
I have succeeded in compiling voxblox-plusplus with "catkin build mask_rcnn_ros depth_segmentation gsm_node -j1 -l1" Thank you very much
