### ISSUE TITLE
opencv3_catkin build error

### ISSUE THREAD

**Issue by captjulian** [ethz-asl/voxblox-plusplus#81]
Hi, Thanks for sharing the great work !!

when I built the package, it gave me this opencv3_catkin problem.

Do you have any idea to solve it?

Much Thanks!!
![error](https://user-images.githubusercontent.com/33579464/81762172-416b1f00-94cc-11ea-82e6-7bd8771d7980.png)

**Comment by nonlinear1** [comment]
I also get some errors when I compile the opencv3_catkin package. Maybe, we can discuss.  Do you have e-mail or wechat?

**Comment by captjulian** [comment]
ok, my email is luliang9211@gmail.com

**Comment by margaritaG** [comment]
@captjulian @nonlinear1 

It seems to be an OpenCV + CMake related error (https://answers.opencv.org/question/189411/opencv-cmake-error/) 

What CMake version are you using?

**Comment by captjulian** [comment]
the CMake version I use is 3.10.2

**Comment by margaritaG** [comment]
@captjulian I am using CMake 3.12.4, maybe you could give that a try.

Anyhow, from the question thread I linked above it seems that a potential problem is building your package within a directory structure that contains special characters. For example, if you created a folder whose name contains "voxblox++" and placed all the packages in it, you might encounter this issue.

Try getting rid of any special characters (e.g. +, /, ') in the names of all parent directories of opencv3_catkin and see if this solves the issue.

**Comment by captjulian** [comment]
thanks a lot.
 
It is because I use the name of the fold as voxblox++ and solved after removing the "++" .
