### ISSUE TITLE
run errors!

### ISSUE THREAD

**Issue by nonlinear1** [ethz-asl/voxblox-plusplus#84]
When I run the asl_office_floor.bag with the command"roslaunch gsm_node asl_office_floor_dataset.launch bag_file:=/home/manifold/catkin_ws/asl_office_floor.bag" 
It give me the errors:
IOError: Unable to open file (truncated file: eof = 229376, sblock->base_addr = 0, stored_eof = 257557808)
[mask_rcnn-2] process has died [pid 12503, exit code 1, cmd /home/manifold/catkin_ws/src/mask_rcnn_ros/scripts/mask_rcnn_node.py ~input:=rgb_image_sub_topic __name:=mask_rcnn __log:=/home/manifold/.ros/log/d70dfdf8-a970-11ea-a263-708bcdbe1b95/mask_rcnn-2.log].
log file: /home/manifold/.ros/log/d70dfdf8-a970-11ea-a263-708bcdbe1b95/mask_rcnn-2*.log
ang the picture for my errors:
![Screenshot from 2020-06-08 18-14-56](https://user-images.githubusercontent.com/19766939/84020002-ab37f500-a9b4-11ea-9597-f504c8310016.png)

Someone know why?And give me some suggestion for solving it! Thank you very much!

**Comment by margaritaG** [comment]
@nonlinear1 It seems that the `mask_rcnn` node cannot properly read the required pretrained model file `mask_rcnn_coco.h5`.

If the node cannot find the model file on disk, it will first download it. It could be that the model file you downloaded got corrupted (for example the download was interrupted), so just try manually deleting it (it should be in your `~/.ros/` directory) and let the node download it again.

**Comment by nonlinear1** [comment]
Thank you margaritaG, you are right!

**Comment by upasana27** [comment]
@margaritaG Can you please help regarding where the .ros directory is located? I can not find the .h5 file you referred to and ran into the same error.
