### ISSUE TITLE
OSError: Cannot load environment from resultspace "/opt/ros/melodic"

### ISSUE THREAD

**Issue by mathmax12** [ethz-asl/voxblox-plusplus#86]
Thanks for the nice work.
I am trying to reproduce the paperwork but got some difficult time setting up the environment.

I got some error after the catkin config and didn't find much useful info...

```
Linux:~/catkin_ws$ **catkin config --extend /opt/ros/melodic/ --merge-devel**
Traceback (most recent call last):
  File "/home/xtree/anaconda3/lib/python3.8/site-packages/catkin_tools/verbs/catkin_config/cli.py", line 144, in main
    context = Context.load(
  File "/home/xtree/anaconda3/lib/python3.8/site-packages/catkin_tools/context.py", line 247, in load
    ctx.load_env()
  File "/home/xtree/anaconda3/lib/python3.8/site-packages/catkin_tools/context.py", line 442, in load_env
    extended_env = get_resultspace_environment(self.extend_path, quiet=False)
  File "/home/xtree/anaconda3/lib/python3.8/site-packages/catkin_tools/resultspace.py", line 93, in get_resultspace_environment
    raise IOError(
OSError: Cannot load environment from resultspace "/opt/ros/melodic" because it does not appear to be a catkin-generated resultspace (missing .catkin marker file).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xtree/.local/bin/catkin", line 8, in <module>
    sys.exit(main())
  File "/home/xtree/anaconda3/lib/python3.8/site-packages/catkin_tools/commands/catkin.py", line 272, in main
    catkin_main(sysargs)
  File "/home/xtree/anaconda3/lib/python3.8/site-packages/catkin_tools/commands/catkin.py", line 267, in catkin_main
    sys.exit(args.main(args) or 0)
  File "/home/xtree/anaconda3/lib/python3.8/site-packages/catkin_tools/verbs/catkin_config/cli.py", line 167, in main
    print('error: could not configure catkin workspace: %s' % exc.message)
AttributeError: 'OSError' object has no attribute 'message
```

**Comment by mathmax12** [comment]
After exhausting the search, I still cannot find a solution for this.
Anyhow, I skipped this step and continued until the build stage. There is no other issue during these steps.
But I got some error during the build stage:
`(base) xtree@xtree-Linux:~/catkin_ws/src$ catkin build mask_rcnn_ros depth_segmentation gsm_node -j4
-------------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/melodic
Workspace:                   /home/xtree/catkin_ws
-------------------------------------------------------------------------------
Build Space:        [exists] /home/xtree/catkin_ws/build
Devel Space:        [exists] /home/xtree/catkin_ws/devel
Install Space:      [unused] /home/xtree/catkin_ws/install
Log Space:          [exists] /home/xtree/catkin_ws/logs
Source Space:       [exists] /home/xtree/catkin_ws/src
DESTDIR:            [unused] None
-------------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-------------------------------------------------------------------------------
Additional CMake Args:       -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        -j4
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-------------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-------------------------------------------------------------------------------
Workspace configuration appears valid.
-------------------------------------------------------------------------------
[build] Found '38' packages in 0.0 seconds.                                                                                                         
[build] Package table is up to date.                                                                                                                
Starting  >>> catkin_simple                                                                                                                         
Starting  >>> mask_rcnn_ros                                                                                                                         
Starting  >>> tf2_msgs                                                                                                                              
Finished  <<< catkin_simple                       [ 0.1 seconds ]                                                                                   
Starting  >>> eigen_catkin                                                                                                                          
Starting  >>> gflags_catkin                                                                                                                         
Finished  <<< eigen_catkin                        [ 0.2 seconds ]                                                                                   
Finished  <<< gflags_catkin                       [ 0.2 seconds ]                                                                                   
Finished  <<< mask_rcnn_ros                       [ 0.4 seconds ]                                                                                   
Finished  <<< tf2_msgs                            [ 0.6 seconds ]                                                                                   
Starting  >>> opencv3_catkin                                                                                                                        
Starting  >>> pcl_catkin                                                                                                                            
Starting  >>> voxblox_msgs                                                                                                                          
Starting  >>> vpp_msgs                                                                                                                              
Finished  <<< opencv3_catkin                      [ 0.3 seconds ]                                                                                   
Finished  <<< vpp_msgs                            [ 0.6 seconds ]                                                                                   
Starting  >>> glog_catkin                                                                                                                           
Finished  <<< voxblox_msgs                        [ 0.5 seconds ]                                                                                   
Finished  <<< glog_catkin                         [ 0.2 seconds ]                                                                                   
Starting  >>> tf2                                                                                                                                   
Finished  <<< tf2                                 [ 0.5 seconds ]                                                                                   
Starting  >>> eigen_checks                                                                                                                          
Finished  <<< eigen_checks                        [ 0.2 seconds ]                                                                                   
Starting  >>> tf2_eigen                                                                                                                             
Starting  >>> tf2_py                                                                                                                                
Finished  <<< tf2_eigen                           [ 0.2 seconds ]                                                                                   
Starting  >>> minkindr                                                                                                                              
Finished  <<< minkindr                            [ 0.1 seconds ]                                                                                   
Finished  <<< tf2_py                              [ 0.4 seconds ]                                                                                   
Starting  >>> minkindr_conversions                                                                                                                  
Starting  >>> voxblox                                                                                                                               
Finished  <<< minkindr_conversions                [ 0.2 seconds ]                                                                                   
Starting  >>> tf2_ros                                                                                                                               
Finished  <<< voxblox                             [ 0.3 seconds ]                                                                                   
Finished  <<< tf2_ros                             [ 0.5 seconds ]                                                                                   
Starting  >>> voxblox_rviz_plugin                                                                                                                   
Finished  <<< voxblox_rviz_plugin                 [ 0.9 seconds ]                                                                                   
____________________________________________________________________________________________________________________________________________________
Errors     << pcl_catkin:make /home/xtree/catkin_ws/logs/pcl_catkin/build.make.002.log                                                           
/usr/lib/x86_64-linux-gnu/libSM.so: undefined reference to `uuid_unparse_lower@UUID_1.0'
/usr/lib/x86_64-linux-gnu/libSM.so: undefined reference to `uuid_generate@UUID_1.0'
collect2: error: ld returned 1 exit status
make[5]: *** [bin/pcl_pcd_grabber_viewer] Error 1
make[4]: *** [tools/CMakeFiles/pcl_pcd_grabber_viewer.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [all] Error 2
make[2]: *** [pcl_src-prefix/src/pcl_src-stamp/pcl_src-build] Error 2
make[1]: *** [CMakeFiles/pcl_src.dir/all] Error 2
make: *** [all] Error 2
cd /home/xtree/catkin_ws/build/pcl_catkin; catkin build --get-env pcl_catkin | catkin env -si  /usr/bin/make --jobserver-fds=4,5 -j; cd -
....................................................................................................................................................
Failed     << pcl_catkin:make                     [ Exited with code 2 ]                                                                            
Failed    <<< pcl_catkin                          [ 3 minutes and 52.4 seconds ]                                                                    
Abandoned <<< pcl_conversions                     [ Unrelated job failed ]                                                                          
Abandoned <<< pcl_ros                             [ Unrelated job failed ]                                                                          
Abandoned <<< depth_segmentation                  [ Unrelated job failed ]                                                                          
Abandoned <<< global_segment_map                  [ Unrelated job failed ]                                                                          
Abandoned <<< voxblox_ros                         [ Unrelated job failed ]                                                                          
Abandoned <<< gsm_node                            [ Unrelated job failed ]                                                                          
[build] Summary: 18 of 25 packages succeeded.                                                                                                       
[build]   Ignored:   13 packages were skipped or are blacklisted.                                                                                   
[build]   Warnings:  None.                                                                                                                          
[build]   Abandoned: 6 packages were abandoned.                                                                                                     
[build]   Failed:    1 packages failed.                                                                                                             
[build] Runtime: 3 minutes and 53.6 seconds total.                                                                                                  
`

**Comment by mathmax12** [comment]
I found that this issue is caused by the anaconda, which hides the system libs.
After removing the anaconda, build finished with below.
There are some ignored and warnings. Are these normal?

.```
...................................................................................................................................................
Finished  <<< gsm_node                            [ 41.4 seconds ]                                                                                  
[build] Summary: All 25 packages succeeded!                                                                                                         
[build]   Ignored:   13 packages were skipped or are blacklisted.                                                                                   
[build]   Warnings:  11 packages succeeded with warnings.                                                                                           
[build]   Abandoned: None.                                                                                                                          
[build]   Failed:    None.                                                                                                                          
[build] Runtime: 13 minutes and 39.5 seconds total.                                                                                                 
[build] Note: Workspace packages have changed, please re-source setup files to use them.
```

**Comment by margaritaG** [comment]
@mathmax12 I am glad you could solve the issue by yourself. Indeed, ROS + Python + Anaconda might not always fit nicely together.

The warnings are normal, do not worry about them.

**Comment by mujinsong** [comment]
How to get to extension is not none?i try to `catkin config --extend /opt/ros/dashing`,but not solved
