### ISSUE TITLE
Failed to save .ply

### ISSUE THREAD

**Issue by wang1104014663** [ethz-asl/voxblox-plusplus#89]
I want save th map. So I refer to the [wiki.]( https://github.com/ethz-asl/voxblox-plusplus/wiki/The-voxblox-plusplus-node)  
I revise the  asl_office_floor.yaml as following:
`publishers:
  publish_scene_map: true
  publish_scene_mesh: true
meshing:
  visualize: true
  update_mesh_every_n_sec: 2.0
  publish_scene_mesh: true
  mesh_filename: "sample_office.ply"
  multiple_visualizers: true`
However,we do not have .ply file in .ros.

**Comment by margaritaG** [comment]
@wang1104014663 

Your parameter settings in `asl_office_floor.yaml` look good.

However, for a PLY file to be exported to disk in the .ros folder in your home directory you have to manually call the `generate_mesh` service. You can do that either from command line or from the rqt GUI. Did you trigger the service call? 

When you do, you should see the node log something like this:
```
I0920 20:05:47.673761 16861 controller.cpp:992] Output file as PLY: sample_office.ply
```

According to your settings, the actual name of the PLY file will be "merged_sample_office.ply", and you should additionally see three other PLY files, more info on this in the [wiki](https://github.com/ethz-asl/voxblox-plusplus/wiki/The-voxblox-plusplus-node#services).

**Comment by ChiyuanFeng** [comment]
> 

Hello Sir, could you give more info about how to call the generate_mesh service? How can I call this in the command line?

**Comment by ChiyuanFeng** [comment]
> > 
> 
> Hello Sir, could you give more info about how to call the generate_mesh service? How can I call this in the command line?

Let me answer my own question in case someone may need this.
rosservice call /gsm_node/generate_mesh
