### ISSUE TITLE
Failed    <<< gflags_catkin，opencv3_catkin

### ISSUE THREAD

**Issue by zhaoyu19920930** [ethz-asl/voxblox-plusplus#90]
Hi， I am configuring the environment, when I run the following commond:
zhaoyu@zhaoyu:~/catkin_ws/src$ catkin build depth_segmentation
it will show "Failed    <<< gflags_catkin，opencv3_catkin"
I have tried a whole day to deal the issue, but find no effective solutions.
Could you give me some tips to solve the problem? Thanks a lot.

**Comment by margaritaG** [comment]
@zhaoyu19920930 could you post the errors that cause the build of the gflags_catkin and opencv3_catkin packages to fail?

At any rate, something always worth trying is a clean re-install by following the instructions in [the Wiki](https://github.com/ethz-asl/voxblox-plusplus/wiki/Installation-on-Ubuntu).

**Comment by zhaoyu19920930** [comment]
Thanks margarita, I have solved the problem, the networks environment caused the error, a clean re-install can effectively solve my problem.

**Comment by zhaoyu19920930** [comment]
Hope to help  people with similar problems, thanks!
