### ISSUE TITLE
Is the source code of incremental object database available?

### ISSUE THREAD

**Issue by LXYYY** [ethz-asl/voxblox-plusplus#91]
Hi, I looked through source code of voxblox++, I noticed it's using semantic and instance label from maskrcnn. But in the paper "Incremental Object Database: Building 3D Models from Multiple Partial Observations", a method is proposed to maintain object database by "pointcloud extraction->keypoints descriptors->matching->merging" processure without semantic information. I am really interested about this part, I want to get source code of it, is it available?

Thank you so much

**Comment by margaritaG** [comment]
@LXYYY Currently the full source code for the Incremental Object Database paper is unfortunately not released, except for the [depth_segmentation](https://github.com/ethz-asl/depth_segmentation/pulls) and the [voxblox++](https://github.com/ethz-asl/voxblox-plusplus) packages.
