### ISSUE TITLE
The meaning of parameters in asl_office_floor.yaml file: camera_position and clip_distances?

### ISSUE THREAD

**Issue by zhaoyu19920930** [ethz-asl/voxblox-plusplus#92]
Hi, I want to make the semantic map using my own bag package, but I don't know how to configur the paramters on the yaml file.
Cause I cannot understand the meaning of the parameters, does the camera_position means pose? What the other one——clip_distance?
If anyone knows, I will be appreciate for your reply! Thanks.

**Comment by margaritaG** [comment]
@zhaoyu19920930 

Unfortunately, we are still missing nice documentation about the individual parameters for the ROS node.

However, a lot of the core parameters are already set to good default values in the `default.yaml` config file, and the ones that are more likely to be custom for each scene are exposed in configs like the `asl_office_floor.yaml` and `scenenn.yaml`, and have (hopefully) intuitive enough names.

To answer your question: the parameters `meshing/visualizer_parameters/camera_position` and `meshing/visualizer_parameters/clip_distances` are just parameters used by the interactive visualizer. Together, they define which view the visualizer is set to. They simply enable nice visualizations, but are not needed for the node logic.

**Comment by zhaoyu19920930** [comment]
Thanks for your nice reply, margaritaG. I have understood the meaning of the paremeters confused me so long.
Small suggestion, you can add detailed documentation if convenient, such that more and more people can learn your excellent work easily.
