### ISSUE TITLE
Cannot build the expected maps

### ISSUE THREAD

**Issue by zhaoyu19920930** [ethz-asl/voxblox-plusplus#93]
Hi, I have run your project successfully on my PC. The instances you given can construct perfect semantic map.
When we record our own bag package,  we encounter some problems using the recorded bag package,.
we analysis the reasons:
(1) the camera position, I cannot confirm the camera position is correct, here is the calculation process:
get the pose of the first frame of the bag package, transform it into camera positon.
(2)the sensor, I used the mynteye camera record the bag package, its precision is too low, then I changed realsense camera, the reconstructed map cannot still satisfy my expectation.
Could you give me some clues, thanks a lot.

**Comment by margaritaG** [comment]
@zhaoyu19920930 

Voxblox++ does not perform camera pose tracking, it relies on you to supply it with the camera poses associated with each frame via TF messages. So when you feed in your own recorded bag, make sure that the bag contains TF messages describing the camera pose associated with each incoming RGB-D frame ("associated" here means that the RGB-D image messages specify the needed frame in the `frame_id` field).

As for the realsense camera, I believe we have successfully used the RGB-D stream from a Realsense D435 to reconstruct dense enough object-level maps of tabletop and maybe even room-sized environments, so I do not see a clear reason why it should not work for you. What exactly are you not happy about in the reconstructed map?

**Comment by zhaoyu19920930** [comment]
Thanks for you nice reply, margaritaG. 
My bag contains TF messages, and the RGB-D image messages specify the needed frame in the frame_id field. My first question  is solved.
When I cannot reconstruct map successfully, I started to study the code of the _depth segementation node_ .Here is my understanding on this node:
(1)this node use the depth image as input, create several middle maps: depth map, depth_discontinuity map, max_distance map, min_convexity, normals map;
(2)then use the middle maps create the final_edge map;
(3)finally use the final_edge map, rgb image, mask_rcnn results generate the label map.

If my understanding has some incorrect points, please correct me.

My confusions:
(1)I find in your '/catkin_ws/src/depth_segmentation/depth_segmentation/cfg/realsense_config.yaml' file, you give the paremetes:  'max_distance_display: false',
‘max_distance_exclude_nan_as_max_distance: false’
’max_distance_ignore_nan_coordinates: false‘

that is to say, you don't use them, can you explain the meaning of max_distance map? 

Many thanks！
