### ISSUE TITLE
Blank Map Occurred

### ISSUE THREAD

**Issue by hyclover** [ethz-asl/voxblox-plusplus#95]
After build the voxblox++, I run the basic demo as you write :roslaunch gsm_node scenenn_dataset.launch bag_file:=/path/to/scenenn_231.bag. But only blank map1 occurred, and the output of the terminal: 
 [RUNNING]  Bag Time:    186.235716   Duration: 186.202200 / 186.315444          [RUNNING]  Bag Time:    186.249248   Duration: 186.215732 / 186.315444          [RUNNING]  Bag Time:    186.269265   Duration: 186.235749 / 186.315444          [RUNNING]  Bag Time:    186.282763   Duration: 186.249247 / 186.315444          [RUNNING]  Bag Time:    186.302781   Duration: 186.269265 / 186.315444          [RUNNING]  Bag Time:    186.316280   Duration: 186.282764 / 186.315444               
Done.
[bag-5] process has finished cleanly
log file: /home/heying/.ros/log/05b47770-0abc-11eb-b5d6-086266293006/bag-5*.log

**Comment by hyclover** [comment]
I have manually download the pretrained weights _mask_rcnn_coco.h5_ and run the default demo command again. I ran out this problem:
`E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-10-10 16:16:33.405795: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
`

my device info:
ubuntu16.04
cuda10
cudnn7.4
Nvidia RTX2070 SUPER

I refer to the solution in [https://github.com/tensorflow/tensorflow/issues/24496](url), but I don't know which file should the code  _gpu_options.allow_growth = True_  can write in? 
I appreciate your efforts and time, thanks a lot!

**Comment by hyclover** [comment]
I added the code _os.environ['CUDA_VISIBLE_DEVICES'] = '1'_ in source file  _/catkin_ws/src/mask_rcnn_ros/src/mask_rcnn_ros/model.py_ and it works finally. But the effect the map I obtained is bad. The dataset I used is SceneNN.

**Comment by jieunko** [comment]
@hyclover I'm having the same problem..right now did you able to solve the problem?
