### ISSUE TITLE
Check failed: neighborhood_size >= 1u (0 vs. 1)

### ISSUE THREAD

**Issue by Chun-Chieh-Wang** [ethz-asl/voxblox-plusplus#98]
Hello, thank you for publishing this awesome work. I'm currently trying to use Zed2 camera as input and launch yumi.launch with ROS melodic. I encountered the problem below and not knowing how to solve it. Can anyone help me with it?

```
F0201 10:35:41.302299 21888 common.h:251] Check failed: neighborhood_size >= 1u (0 vs. 1) 
*** Check failure stack trace: ***
    @     0x7fd2d301ab0d  google::LogMessage::Fail()
    @     0x7fd2d301c9b1  google::LogMessage::SendToLog()
    @     0x7fd2d301a63d  google::LogMessage::Flush()
    @     0x7fd2d301d389  google::LogMessageFatal::~LogMessageFatal()
    @     0x55aa20f52e3f  depth_segmentation::findNeighborhood()
    @     0x55aa20f55905  _ZN18depth_segmentation17computeOwnNormalsERKNS_19SurfaceNormalParamsERKN2cv3MatEPS4_._omp_fn.0
    @     0x7fd2d069396e  (unknown)
    @     0x7fd2d20da6db  start_thread
    @     0x7fd2cfe0c71f  clone
[depth_segmentation_node-2] process has died [pid 21034, exit code -6, cmd /home/robot/catkin_ws/devel/lib/depth_segmentation/depth_segmentation_node __name:=depth_segmentation_node __log:=/home/robot/.ros/log/7806c9a6-62b7-11eb-b665-f2955cc0fcc3/depth_segmentation_node-2.log].
log file: /home/robot/.ros/log/7806c9a6-62b7-11eb-b665-f2955cc0fcc3/depth_segmentation_node-2*.log
```

**Comment by margaritaG** [comment]
@Chun-Chieh-Wang 

It's not the voxblox-plusplus package that is failing, but the depth_segmentation package. More specifically, the depth_segmentation_node. 

The depth_segmentation_node starts by estimating a normal for each point in a depth image by looking at its neighborhood. Some neighboring points can be discarded from the normal computation if they are too far in an Euclidean sense. Your error seems to suggest that there were no neighboring points left after this filtering step, from what I understand not even the actual point for which the normal is being computed. My guess is that this is a result of some weird numerical error, or some weird input depth map.

I assume this is not something that should happen often, did you try running the pipeline on a different RGB-D sequence?
