### ISSUE TITLE
successfully run this on Ubuntu20.04+python3+RTX3080+tf2.4.1+keras2.4.3

### ISSUE THREAD

**Issue by 565353780** [ethz-asl/voxblox-plusplus#99]
Look at my blog:
https://blog.csdn.net/qq_49466306/article/details/111872619
Hope this will be helpful to you~
Enjoy it~

**Comment by 565353780** [comment]
And more detials, I use:
Ubuntu20.04.2 LTS
/usr/bin/python3.8.5
cuda 11.1(tf with RTX3080 needs to define sm_86, so should keep cuda version >= 11.1)
cudnn 8.0.5
gcc & g++ 9.3.0
cmake 3.16.3

**Comment by liuzhenboo** [comment]
good job!
